steps:
# Install
# - name: 'node'
#   entrypoint: 'yarn'
#   args: [ 'install' ]
# Tests
# - name: 'node'
#   entrypoint: 'yarn'
#   args: [ 'test' ]
# Build image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/serverless-auth-service', '-f', './Dockerfile', '.' ]
# Push image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/serverless-auth-service' ]
# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run',
    'deploy',
    'serverless-auth-service',
    '--image', 'gcr.io/$PROJECT_ID/serverless-auth-service',
    '--region', 'us-east1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--port', '3000',
    '--timeout', '10m' ]