services:
 app:
    container_name: migration-assistant-server
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./:/app
